version: '3'

volumes:
  mysql_db_1:
  mysql_db_2:
  mongo_db:

services:

  mongo_database:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo_database
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo_database:27017/

  mysql_database_1:
    image: mysql:8.0.34
    volumes:
      - mysql_db_1:/var/lib/mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root1234
      - MYSQL_ROOT_PASSWORD=root1234

  mysql_database_2:
    image: mysql:8.0.34
    volumes:
      - mysql_db_2:/var/lib/mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root1234
      - MYSQL_ROOT_PASSWORD=root1234

  eureka-server:
    image: bib_eureka_server
    build: ./eureka-server
    restart: always
    ports:
      - "8761:8761"

  api-gateway:
    image: bib_api_gateway
    build: ./gateway
    restart: always
    depends_on:
      - eureka-server
    ports:
      - "8089:8089"
    environment:
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
    links:
      - eureka-server

  clientes:
    image: bib_clientes
    build: ./clientes
    restart: always
      #ports:
    #- "8084:8084"
    depends_on:
      - mongo_database
      - eureka-server
    environment:
      spring.data.mongodb.uri: mongodb://root:example@mongo_database:27017/clientes?authSource=admin
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
    links:
      - eureka-server

  libros:
    image: bib_libros
    build: ./libros
    restart: always
      #ports:
    #- "8083:8083"
    depends_on:
      - mysql_database_1
      - eureka-server
    environment:
      spring.datasource.url: jdbc:mysql://mysql_database_1:3306/libros?createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: root1234
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
    links:
      - eureka-server

  prestamos:
    image: bib_prestamos
    build: ./prestamos
    restart: always
      #ports:
    #- "8082:8082"
    depends_on:
      - mysql_database_2
      - eureka-server
    environment:
      spring.datasource.url: jdbc:mysql://mysql_database_2:3306/prestamos?createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: root1234
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
    links:
      - eureka-server
